In [19]:
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [20]:
df = pd.read_csv(r"C:\Users\Hari\OneDrive\Desktop\amazon_project\amazon_products_sales_data_cleaned (1).csv")

In [26]:
df.head(3)

,product_title,product_rating,total_reviews,purchased_last_month,discounted_price,original_price,is_best_seller,is_sponsored,has_coupon,buy_box_availability,delivery_date,sustainability_tags,product_image_url,product_page_url,data_collected_at,product_category,discount_percentage
0,BOYA BOYALINK 2 Wireless Lavalier Microphone f...,4.6,375.0,300.0,89.68,159.00,No Badge,Sponsored,Save 15% with coupon,Add to cart,2025-09-01,Carbon impact,https://m.media-amazon.com/images/I/71pAqiVEs3...,https://www.amazon.com/sspa/click?ie=UTF8&spc=...,2025-08-21 11:14:29,Phones,43.60
1,"LISEN USB C to Lightning Cable, 240W 4 in 1 Ch...",4.3,2457.0,6000.0,9.99,15.99,No Badge,Sponsored,No Coupon,Add to cart,2025-08-29,NaN,https://m.media-amazon.com/images/I/61nbF6aVIP...,https://www.amazon.com/sspa/click?ie=UTF8&spc=...,2025-08-21 11:14:29,Laptops,37.52
2,"DJI Mic 2 (2 TX + 1 RX + Charging Case), Wirel...",4.6,3044.0,2000.0,314.00,349.00,No Badge,Sponsored,No Coupon,Add to cart,2025-09-01,NaN,https://m.media-amazon.com/images/I/61h78MEXoj...,https://www.amazon.com/sspa/click?ie=UTF8&spc=...,2025-08-21 11:14:29,Laptops,10.03

In [64]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 42675 entries, 0 to 42674
Data columns (total 17 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   product_rating        42675 non-null  float64
 1   total_reviews         42675 non-null  int64
 2   purchased_last_month  42675 non-null  int64
 3   discounted_price      42675 non-null  float64
 4   original_price        42675 non-null  float64
 5   discount_percentage   42675 non-null  float64
 6   product_title         42675 non-null  object
 7   is_best_seller        42675 non-null  object
 8   is_sponsored          42675 non-null  object
 9   has_coupon            42675 non-null  object
 10  buy_box_availability  42675 non-null  object
 11  delivery_date         42675 non-null  datetime64[ns]
 12  product_image_url     42675 non-null  object
 13  product_page_url      42675 non-null  object
 14  data_collected_at     42675 non-null  datetime64[ns]
 15  product_category      42675 non-null  object
 16  discounted_amount     42675 non-null  float64
dtypes: datetime64[ns](2), float64(5), int64(2), object(8)
memory usage: 5.5+ MB

### Observations : 1.We observed that there are incorrect data types for the columns in the data 
### 1.1:Column like total_reviews should change from float to integer
### 1.2:purchaced_last_month should change from float to integer
### 1.3:The date columns like dedlivery_date ,date_collected_at are in object should change it to date type

In [23]:
len(df)

42675

In [24]:
df.isnull().sum()*100/len(df)

product_title            0.000000
product_rating           2.399531
total_reviews            2.399531
purchased_last_month    24.630346
discounted_price         4.831869
original_price           4.831869
is_best_seller           0.000000
is_sponsored             0.000000
has_coupon               0.000000
buy_box_availability    34.336262
delivery_date           28.079672
sustainability_tags     92.014060
product_image_url        0.000000
product_page_url         4.848272
data_collected_at        0.000000
product_category         0.000000
discount_percentage      4.831869
dtype: float64

### Observations: As we see the null values percentages columns like more than 45% of nulls should be dropped to get better analysis and insights from the data Columns like(sustainability_tags) and there are other columns like with 24%,28%,34% need to be filled with suitable values.

In [25]:
df.duplicated().sum()

np.int64(0)

### No duplicates in the data

### Action item 1  (Filling the null values with median)

In [28]:
df.describe().T

,count,mean,std,min,25%,50%,75%,max
product_rating,41651.0,4.399431,0.386997,1.00,4.20,4.50,4.70,5.00
total_reviews,41651.0,3087.106000,13030.460133,1.00,82.00,343.00,1886.00,865598.00
purchased_last_month,32164.0,1293.665278,6318.323574,50.00,100.00,200.00,400.00,100000.00
discounted_price,40613.0,243.227289,473.351545,2.16,29.69,84.99,224.00,5449.00
original_price,40613.0,257.611107,496.633495,2.16,32.99,89.00,229.99,5449.00
discount_percentage,40613.0,6.547151,12.744715,0.00,0.00,0.00,8.49,85.42

In [29]:
 df.columns

Index(['product_title', 'product_rating', 'total_reviews',
       'purchased_last_month', 'discounted_price', 'original_price',
       'is_best_seller', 'is_sponsored', 'has_coupon', 'buy_box_availability',
       'delivery_date', 'sustainability_tags', 'product_image_url',
       'product_page_url', 'data_collected_at', 'product_category',
       'discount_percentage'],
      dtype='object')

In [35]:
num_df =  df.select_dtypes(include ="number")
cat_df =  df.select_dtypes(exclude ="number")

In [36]:
cat_df.columns

Index(['product_title', 'is_best_seller', 'is_sponsored', 'has_coupon',
       'buy_box_availability', 'delivery_date', 'sustainability_tags',
       'product_image_url', 'product_page_url', 'data_collected_at',
       'product_category'],
      dtype='object')

In [37]:
num_df.isnull().sum()

product_rating           1024
total_reviews            1024
purchased_last_month    10511
discounted_price         2062
original_price           2062
discount_percentage      2062
dtype: int64

In [41]:
for column in num_df.columns:
    num_df[column]=num_df[column].fillna(num_df[column].median())

In [42]:
num_df.isnull().sum()

product_rating          0
total_reviews           0
purchased_last_month    0
discounted_price        0
original_price          0
discount_percentage     0
dtype: int64

In [45]:
for column in cat_df:
    mode_value = (cat_df[column].mode().values[0])
    cat_df[column]= cat_df[column].fillna(mode_value)

In [47]:
cat_df.isnull().sum()

product_title           0
is_best_seller          0
is_sponsored            0
has_coupon              0
buy_box_availability    0
delivery_date           0
sustainability_tags     0
product_image_url       0
product_page_url        0
data_collected_at       0
product_category        0
dtype: int64

In [85]:
df=pd.concat([num_df,cat_df],axis =1)
df.head(1)

,product_rating,total_reviews,purchased_last_month,discounted_price,original_price,discount_percentage,product_title,is_best_seller,is_sponsored,has_coupon,buy_box_availability,delivery_date,sustainability_tags,product_image_url,product_page_url,data_collected_at,product_category
0,4.6,375.0,300.0,89.68,159.0,43.6,BOYA BOYALINK 2 Wireless Lavalier Microphone f...,No Badge,Sponsored,Save 15% with coupon,Add to cart,2025-09-01,Carbon impact,https://m.media-amazon.com/images/I/71pAqiVEs3...,https://www.amazon.com/sspa/click?ie=UTF8&spc=...,2025-08-21 11:14:29,Phones

### Action item 2(data type conversion)

In [51]:
df['total_reviews'] = df['total_reviews'].astype(int)
df['purchased_last_month'] = df['purchased_last_month'].astype(int)

In [62]:
df['delivery_date']=pd.to_datetime(df['delivery_date'],errors ='coerce')
df['data_collected_at']=pd.to_datetime(df['data_collected_at'],errors ='coerce')

### Action  item 3 (Dropping column with nulls percentage is higher)

In [56]:
df.drop(['sustainability_tags'],axis =1,inplace = True)

### Feature Engineering

In [66]:
df['discounted_amount']=df['original_price'] - df ['discounted_price']
df.head(2)

,product_rating,total_reviews,purchased_last_month,discounted_price,original_price,discount_percentage,product_title,is_best_seller,is_sponsored,has_coupon,buy_box_availability,delivery_date,product_image_url,product_page_url,data_collected_at,product_category,discounted_amount
0,4.6,375,300,89.68,159.00,43.60,BOYA BOYALINK 2 Wireless Lavalier Microphone f...,No Badge,Sponsored,Save 15% with coupon,Add to cart,2025-09-01,https://m.media-amazon.com/images/I/71pAqiVEs3...,https://www.amazon.com/sspa/click?ie=UTF8&spc=...,2025-08-21 11:14:29,Phones,69.32
1,4.3,2457,6000,9.99,15.99,37.52,"LISEN USB C to Lightning Cable, 240W 4 in 1 Ch...",No Badge,Sponsored,No Coupon,Add to cart,2025-08-29,https://m.media-amazon.com/images/I/61nbF6aVIP...,https://www.amazon.com/sspa/click?ie=UTF8&spc=...,2025-08-21 11:14:29,Laptops,6.00

### Observations: We created column called discounted amount that customer received with the help of original price and discounted price

In [68]:
df['estimated_revenue']=df['discounted_price']*df['purchased_last_month']
df.head(2)

,product_rating,total_reviews,purchased_last_month,discounted_price,original_price,discount_percentage,product_title,is_best_seller,is_sponsored,has_coupon,buy_box_availability,delivery_date,product_image_url,product_page_url,data_collected_at,product_category,discounted_amount,estimated_revenue
0,4.6,375,300,89.68,159.00,43.60,BOYA BOYALINK 2 Wireless Lavalier Microphone f...,No Badge,Sponsored,Save 15% with coupon,Add to cart,2025-09-01,https://m.media-amazon.com/images/I/71pAqiVEs3...,https://www.amazon.com/sspa/click?ie=UTF8&spc=...,2025-08-21 11:14:29,Phones,69.32,26904.0
1,4.3,2457,6000,9.99,15.99,37.52,"LISEN USB C to Lightning Cable, 240W 4 in 1 Ch...",No Badge,Sponsored,No Coupon,Add to cart,2025-08-29,https://m.media-amazon.com/images/I/61nbF6aVIP...,https://www.amazon.com/sspa/click?ie=UTF8&spc=...,2025-08-21 11:14:29,Laptops,6.00,59940.0

### Observations:We calculated estimated revenue that company received from sales from last month for each catogery of products

In [78]:
df['percentage_range']=pd.cut(x=df['discount_percentage'],bins =[0,30,50,70,90],labels =["less","medium","high","veryhigh"])
df.head(2)

,product_rating,total_reviews,purchased_last_month,discounted_price,original_price,discount_percentage,product_title,is_best_seller,is_sponsored,has_coupon,buy_box_availability,delivery_date,product_image_url,product_page_url,data_collected_at,product_category,discounted_amount,estimated_revenue,percentage_range
0,4.6,375,300,89.68,159.00,43.60,BOYA BOYALINK 2 Wireless Lavalier Microphone f...,No Badge,Sponsored,Save 15% with coupon,Add to cart,2025-09-01,https://m.media-amazon.com/images/I/71pAqiVEs3...,https://www.amazon.com/sspa/click?ie=UTF8&spc=...,2025-08-21 11:14:29,Phones,69.32,26904.0,medium
1,4.3,2457,6000,9.99,15.99,37.52,"LISEN USB C to Lightning Cable, 240W 4 in 1 Ch...",No Badge,Sponsored,No Coupon,Add to cart,2025-08-29,https://m.media-amazon.com/images/I/61nbF6aVIP...,https://www.amazon.com/sspa/click?ie=UTF8&spc=...,2025-08-21 11:14:29,Laptops,6.00,59940.0,medium

### Analysis

In [73]:
df['percentage_range'].value_counts()

percentage_range
less        9199
medium      2425
high         548
veryhigh     139
Name: count, dtype: int64

### Observations: With the help of percentage range column created in feature engineering section we have products count which are at different discounted percentages

In [ ]:
df['is_sponsored'].value_counts()

### Observations: we have more organic products(products that are not promoted by amazon) than amazon sponsored

In [82]:
df['product_category'].value_counts()

product_category
Other Electronics      8755
Laptops                8693
Phones                 6563
Cameras                3677
Power & Batteries      2877
TV & Display           2630
Chargers & Cables      1833
Storage                1630
Speakers               1345
Networking             1070
Headphones              997
Printers & Scanners     877
Gaming                  809
Smart Home              465
Wearables               454
Name: count, dtype: int64

### Observations: As from the analysis from category other electronics sold more than the rest

In [84]:
df['product_rating'].describe()

count    42675.000000
mean         4.401844
std          0.382636
min          1.000000
25%          4.200000
50%          4.500000
75%          4.600000
max          5.000000
Name: product_rating, dtype: float64